name: Mangopay playwright tech-task
run-name: Running playwright tests.

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Run-Playwright-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup and Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: Install all needed dependences
        run: npm install
      - name: Init Playwright
        run: npm install playwright
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/