name: Mangopay playwright tech-task
run-name: Running playwright tests.

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Run-Cypress-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup and Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: Install all needed dependences
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests with list reporter
        run: npx playwright test --reporter=list
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/